### ISSUE TITLE
全屏H5时兼容刘海屏

### ISSUE THREAD

**Issue by buddywang** [buddywang/blog#25]
![image](https://user-images.githubusercontent.com/37980587/98495854-198e2580-227b-11eb-80bb-4020c333be07.png)

## 问题
- 假如 H5 页面在 iOS 中占据全屏页面，在这种情况下，除了要兼顾底部小黑条，还要处理页面上部跟状态栏接触的部分，避免内容出现在状态栏上。
## 方法一（适合 IOS）
- 1. 加上 `meta` 头
```
<meta name="viewport" content="(other opts ,)viewport-fit=cover">
```
- 2. 加上 padding
```css
body {
  padding:/* 兼容 iOS < 11.2 */
    constant(safe-area-inset-top)/* 顶部状态栏、底部小黑条（eg: iPhoneX） */
    constant(safe-area-inset-bottom)
    constant(safe-area-inset-right)/* 横屏时的左右不规则屏、小黑条 */
    constant(safe-area-inset-left); 
  padding:/* 兼容 iOS >= 11.2 */
    env(safe-area-inset-top)
    env(safe-area-inset-bottom)
    env(safe-area-inset-right)
    env(safe-area-inset-left); 
}
```
- 3. 针对 fixed 定位的元素，上面的第二步无效，可以在该元素上通过增加 bottom/top/left/right 来实现：
```
.element {
  bottom: calc(@element-height + constant(safe-area-inset-bottom));
  ...
}
```
## 方法二（都适合 👍 ）
需要 APP 端提供能力（JSBridge），前端根据动态获取状态栏的高度来设置样式
## 参考
- https://www.jianshu.com/p/a1d98f668ed5
- https://www.ldsun.com/h5-fullscreen-webview-adaptation-notch-screen/
- https://developer.mozilla.org/zh-CN/docs/Web/CSS/@viewport/viewport-fit
- https://developer.mozilla.org/zh-CN/docs/Web/CSS/env
